# Включенные правила (если не указаны, используются все)
analyzer_rules:
  - explicit_self
  - unused_import
  
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_collection_literal
  - empty_string
  - expiring_todo
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - strict_fileprivate
  - switch_case_on_newline
  - unneeded_break_in_switch
  - vertical_parameter_alignment
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces

# Отключенные правила (слишком строгие или неактуальные)
disabled_rules:
  - line_length # Часто мешает, лучше отключить
  - file_length # Можно настроить под свой проект
  - function_body_length
  - type_body_length
  - trailing_whitespace
  - identifier_name # Конфликтует с кодстайлом Apple
  - cyclomatic_complexity
  - nesting
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_opening_braces

# Игнорируемые файлы/папки
excluded:
  - Pods
  - Carthage
  - Tests
  - UITests
  - Generated
  - Resources
  - Localizations
  - Fastlane
  - .build
  - DerivedData
